### ISSUE TITLE
Cloud9 default server not powerful enough

### ISSUE THREAD

**Issue by Steve--Hunter** [awslabs/aws-saas-boost#100]
If you are using Cloud9 IDE, for this to work with the 'sh install.sh' step:

1. The default 10G disk will fill up quick with logs, I switched to a 50G
 2. I kept getting error about being low on virtual memory … changed instance type from t2.micro to t2.xlarge (1->4 vCPUs, 1G-16G RAM)

Hope that helps everyone else in their SaaS journey :D

---

**Comment by 4patelr** [comment]
Thanks for sharing to info. The documentation for install using Cloud9 (https://github.com/awslabs/aws-saas-boost/blob/main/docs/install_using_cloud9.md) has instruction to use an instance with at least 4GB memory and how to resize the disk.

**Comment by brtrvn** [comment]
Thanks for taking the time to submit the feedback Steve. Feel free to submit a PR against the documentation if you like, but since this is currently covered by our docs I'm going to close this issue.

**Comment by Steve--Hunter** [comment]
Yes, my bad, please close this.

Thanks

Steve Hunter
+61 438 405 404
