### ISSUE TITLE
Add support for Linux in EC2

### ISSUE THREAD

**Issue by AffiTheCreator** [awslabs/aws-saas-boost#108]
Currently, to run a Linux instance the only method is by running a Fargate cluster. Depending on the workload of the application a fargate cluster might not be sufficient to respond to the demanding CPU and memory, and it would be more beneficial to have an EC2 instance instead of Fargate.

### Use Case

1. When there is necessity to have more control over the instance
2. The application workload might demand a more powerful requirements.  

---

This is a :rocket: Feature Request

**Comment by brtrvn** [comment]
EC2 launch type support for Linux workloads will have basic support in the upcoming release. We will still need to update the UI and provide a way to choose different EC2 instance types.

We can also now work on Fargate launch type support for Windows workloads.

**Comment by brtrvn** [comment]
Resolved with #259
