### ISSUE TITLE
Fix to database instance type in "Getting started" guide under "Configure AWS SaaS Boost for the Sample Application" section

### ISSUE THREAD

**Issue by hariohmprasath** [awslabs/aws-saas-boost#15]
**Link to the page**
[Configure AWS SaaS Boost for the Sample Application](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#configure-aws-saas-boost-for-the-sample-application)

**Description**
A slight change to database instance type mentioned in the below sentence

`"Select any of the available databases (MariaDB with a db.t2.micro instance class will provision the fastest)"`

Whereas the smallest instance type part of the instance type dropdown is `db.t3.micro` so this needs to be updated in the getting started guide

Here is the screenshot of it
![image](https://user-images.githubusercontent.com/2615325/118087269-2569ba00-b37a-11eb-8234-17d980b003c8.png)

---

This is a 📕 documentation issue

**Comment by brtrvn** [comment]
Thanks for the head's up Hari. It's a simple fix. I believe we refer to the basic instructions on getting the sample app up and running in multiple docs, so we should review the user guide, getting started, and the developer guide for the same fix.

**Comment by hariohmprasath** [comment]
> Thanks for the head's up Hari. It's a simple fix. I believe we refer to the basic instructions on getting the sample app up and running in multiple docs, so we should review the user guide, getting started, and the developer guide for the same fix.

I have taken care of those changes as well, you can see the update in the pull request

**Comment by brtrvn** [comment]
Resolved with merge of PR #16
