### ISSUE TITLE
set up problem

### ISSUE THREAD

**Issue by ptthuc26** [awslabs/aws-saas-boost#151]
I followed the setup [instructions](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md).
i completed set up tooling.
But when i run script .\install.ps1, then it got error like this 
![image](https://user-images.githubusercontent.com/55550757/142385091-06e71062-43e6-4b2c-aa44-2e1bd7e1c446.png)

please help me. thank you

**Comment by brtrvn** [comment]
Hello @ptthuc26 - can you look at the installer log file to get more details on what exactly is failing for you?

Also, you can use a [Cloud9 environment](https://github.com/awslabs/aws-saas-boost/blob/main/docs/install_using_cloud9.md) to run the installer if your local workstation is having problems.

**Comment by ptthuc26** [comment]
> Hello @ptthuc26 - can you look at the installer log file to get more details on what exactly is failing for you?
> 
> Also, you can use a [Cloud9 environment](https://github.com/awslabs/aws-saas-boost/blob/main/docs/install_using_cloud9.md) to run the installer if your local workstation is having problems.

![image](https://user-images.githubusercontent.com/55550757/142791187-f8cde38e-a6a8-4ec2-ae6c-286fed4d84dd.png)
hi @brtrvn , this is the installer log file. i tried cloud9 but still the same error. please help me solve this problem.

Thank you.

**Comment by PoeppingT** [comment]
Hi @ptthuc26 , this looks to be only a section of your installer log file. In particular, we're looking for any error messages in the `saas-boost-install.log` file that might point to what's going wrong here. Can you explain in detail which step in the [startup instructions](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md) you are getting stuck on? Are there any instructions that don't make sense?

**Comment by aquibchiniwala** [comment]
I was having the same issue. After debugging the code I found that there is an issue with the unit test case located at "installer\src\test\java\com\amazon\aws\partners\saasfactory\saasboost\SaaSBoostInstallTest.java".

Removing the last assert statement i.e. 

for (Map.Entry<String, String> entry : expected.entrySet()) {
    assertEquals(entry.getKey() + " equals " + entry.getValue(), entry.getValue(), actual.get(entry.getKey()));
}

from the file and running the install.ps1 script solved my issue.

Maybe @PoeppingT you could check what is the issue with the test case "testGetCloudFormationParameterMap" where keyboard input is checked.
