### ISSUE TITLE
#/Volumes/0: extraneous key [EfsVolumeConfiguration] is not permitted

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-saas-boost#179]
any idea?

```Resource template validation failed for resource ECSTaskDefinition as the template has invalid properties. Please refer to the resource documentation to fix the template. Properties validation failed for resource ECSTaskDefinition with message: #/Volumes/0: extraneous key [EfsVolumeConfiguration] is not permitted```

**Comment by PoeppingT** [comment]
Hi @cfregly , thanks for opening this bug request! We can more easily help you find an answer to your question if you provide more contextual information. What were you trying to do? If you have created an application, are you using the sample application or one of your own make? What configurations did you select? What steps could one of us on the team follow to see the same failure you saw?

**Comment by brtrvn** [comment]
If you can post your app config (redact any sensitive info), that would help. Issue a GET to your public API endpoint for `settings/config`.

i.e. `curl -w "\n" -H "Authorization: Bearer <JTW token>" https://<api id>.execute-api.<region>.amazonaws.com/v1/settings/config`

You can get your public API endpoint from the Summary page of the admin web app.

You can get the JWT token either by copying it from your web browser's dev tools once you've logged into the admin web app or you can issue a POST to `/users/token` with a request body of `{"username": "admin", "password": "<your admin password>"}` and then use the `accessToken` value as the JTW token value.

**Comment by cfregly** [comment]
sample app, yes.

followed instructions here:  https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md

**Comment by cfregly** [comment]
possibly related to this CDK issue?  https://github.com/aws/aws-cdk/issues/15025

**Comment by brtrvn** [comment]
Closed with PR #183
