### ISSUE TITLE
Support multiple Docker Container

### ISSUE THREAD

**Issue by Yuutakasan** [awslabs/aws-saas-boost#190]
Support for systems that are split across multiple Dockers

### Use Case
When developing a frontend with NuxtJS and a backend with laravel api,
we want to manage multiple containers instead of a single container.

### Proposed Solution
Allow the two Docker files registered in ECR to be specified when registering the service.

---

This is a :rocket: Feature Request

**Comment by PoeppingT** [comment]
Hi @Yuutakasan , thanks for opening this feature request! I'm pleased to let you know the team is already working on this feature request, please see the discussion here: https://github.com/awslabs/aws-saas-boost/discussions/25

**Comment by Yuutakasan** [comment]
@PoeppingT 
Thanks. I'll refer to the discussion.
