### ISSUE TITLE
custom environment variables support for each service on docker.

### ISSUE THREAD

**Issue by Yuutakasan** [awslabs/aws-saas-boost#191]
## :question: General Issue
As for the environment variables for the database, I found out that they are accepted in the admin panel, and I can proceed with the setup, but I would like to add environment variables for the initial setup so that I can set them up.

### The Question
When launching Docker, I would like to set additional environment variables for each contract.

### Environment

  - **AWS SaaS Boost Version:** latest

**Comment by PoeppingT** [comment]
Hey @Yuutakasan , thanks for opening this feature request! We have a feature for giving your containers access to configuration already, see the conversation in https://github.com/awslabs/aws-saas-boost/issues/172 for more information.

We believe that having a easily dynamic configuration be separate from the running code in your containers is a development best practice and so have chosen not to implement a feature to directly inject environment variables into the ECS Task Definition, as the container would need to be redeployed on each configuration change.

One possible feature that could be built into Boost to address what you're looking for would be to implement a connector with AWS AppConfig to allow Boost users to supply configurations to each of their Tenant applications individually, allowing for dynamic configuration controls. The configurations could be managed as part of an additional "Tenant-specific configurations" as part of the Tenant microservice which container applications would reach out to to retrieve the latest configurations at regular intervals. We always welcome Pull Requests if you're interested in developing such a feature.
