### ISSUE TITLE
Remove unnecessary dependencies in sub-modules

### ISSUE THREAD

**Issue by PoeppingT** [awslabs/aws-saas-boost#194]
In particular, we need to remove dependencies that may introduce perception of vulnerabilities. For example, we've received dependabot PRs like https://github.com/awslabs/aws-saas-boost/pull/192 which upgrades the declared postgresql dependency in the `rds-bootstrap` custom resource, despite the fact that that dependency is used nowhere in the resource.

**Comment by brtrvn** [comment]
That dependency is used if the database engine SaaS Boost is bootstraping during tenant onboarding is a PostgreSQL database. Same is true for the other database drivers. We determine the correct driver at runtime and load it with `java.sql.DriverManager`.
