### ISSUE TITLE
Tiers for Onboarding creation form have incorrect defaults and aren't properly connected

### ISSUE THREAD

**Issue by PoeppingT** [awslabs/aws-saas-boost#208]
When trying to onboard a tenant using RC0, the default tier in the Onboarding create form has an incorrect default value (`'default '` instead of `'default'`) and the tier that should be pulled out of config is improperly wired up, meaning that the default value will always be used.

### Reproduction Steps

1. Install a v2.0.0-RC0 environment
2. Create an app config with a single service, and follow `getting-started.md` to upload the sample application into the created ECR repository
3. Attempt to onboard a tenant

### What did you expect to happen?

The onboarding request should eventually move to Complete

### What actually happened?

The onboarding request is stuck in validation. Logs for the `sb-<env>-onboarding-validation` lambda show the following:
```
Missing tier configuration for service 'xxx' tier 'default '
```

More information [here](https://github.com/awslabs/aws-saas-boost/discussions/206)

### Environment

  - **AWS Region  :** any
  - **AWS SaaS Boost Version :** v2.0.0-RC0
  - **Workload OS  (Linux or Windows) :** any

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Resolved with commit b386c05
