### ISSUE TITLE
Installing a second SaaS Boost environment in the same account fails

### ISSUE THREAD

**Issue by PoeppingT** [awslabs/aws-saas-boost#213]
In the multi-container branch we added a CloudFormation Macro to SaaS Boost in order to support creating individual ECR repositories for each service. This is implemented as a CloudFormation Macro, Lambda Function, and CloudWatch LogGroup created with a specific set of names in the `saas-boost.yaml` base stack. This macro is then referred to in the `Transform` section of the `saas-boost-core.yaml` core stack: duplicating the service-specific resources for each service listed in the `ApplicationServices` parameter.

This implementation works, but has a small problem: because the base stack always attempts to create a macro and related resources with the same names, attempting to create two environments in the same account fails because the macro already exists.

We cannot give the macro a variable name because ["intrinsic functions included in the template are evaluated after any macros"](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html#template-macros-considerations) and [variable substitution functions are considered intrinsic](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html).

### Reproduction Steps

1. Create a multi-container SaaS Boost environment using the installer and the multi-container branch. Any options are vaild, no need to create an AppConfig or upload any container images.
2. Create a second environment. You will see the base stack fail because the macro resources already exist

### What did you expect to happen?

I should be able to install as many SaaS Boost environments as my AWS limits allow.

### What actually happened?

You will see the base stack fail because the macro resources already exist

### Environment

  - **AWS Region  :** us-west-2, but this happens in any region
  - **AWS SaaS Boost Version :** v2.0.0-rc0, v2.0.0-rc1, multi-container branch
  - **Workload OS  (Linux or Windows) :** N/A

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Resolved with PR #283
