### ISSUE TITLE
Cannot use Tenant Detail Actions via Admin UI

### ISSUE THREAD

**Issue by tieujason330** [awslabs/aws-saas-boost#216]
Admin UI tenant actions (enable, disable, delete) do not work.

### Reproduction Steps

Delete:
1. Access Admin UI
2. Create a new Tenant
3. Go to Tenant Detail page
4. Click 'Delete' in Actions dropdown
5. No delete confirmation modal appears

Enable/Disable actions fail due to CORS errors when triggered via Admin UI.

### What did you expect to happen?

Expected delete confirmation modal to appear.

Expected enable/disable actions to work as described.

### What actually happened?

Delete confirmation modal doesn't appear.

Enable/disable actions throw error

### Environment

  - **AWS Region  :** us-esat-1
  - **AWS SaaS Boost Version :** v2.0.0-rc1, v2.0.0-rc0. multi-container
  - **Workload OS  (Linux or Windows) :** mac/linux

### Other

For enable/disable actions, CORS policy blocked because `PATCH` method is not allowed by `Access-Control-Allow-Methods`. Fix by updating `resources/saas-boost-public-ami.yaml`

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Thanks for raising this issue @tieujason330 ! We're aware of this and will be looking into it.

**Comment by PoeppingT** [comment]
This issue is fixed in https://github.com/awslabs/aws-saas-boost/commit/2dd7272c9fa457033b3df0b837e7f53a896bc108, marking as pending-release of v2.0.0.

**Comment by brtrvn** [comment]
Merged into `main`
