### ISSUE TITLE
An issue on update config page

### ISSUE THREAD

**Issue by rnlduaeo** [awslabs/aws-saas-boost#245]
Given the condition that there is no onboarded tenant yet, after setting an app config and submitting that including bootstrap file, when the user tries to update the db version, then the post request post 'null' value of bootstrap file ever since 

### Reproduction Steps

![](https://raw.githubusercontent.com/rnlduaeo/eks-example/main/saasboostbug.gif)

### What did you expect to happen?
my file should be there..

### What actually happened?
null value is there..

### Environment

  - **AWS Region  :**
  - **AWS SaaS Boost Version :**
  - **Workload OS  (Linux or Windows) :**

### Other

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Confirmed this bug is still present in `main`
