### ISSUE TITLE
.\install.ps1 failed

### ISSUE THREAD

**Issue by jrobbins-LiveData** [awslabs/aws-saas-boost#26]
I followed the [setup instructions](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#step-1---set-up-tooling)  with one exception -- my machine already had `node v14.16.1` on it, so I did not install `node v14.15`.
```
.\install.ps1
AWS Region = us-east-2
Building Java Installer with maven
Java Installer build completed
Downloading dependencies for React Web App, please be patient
Download dependencies completed for React Web App
Launch Java Installer for SaaS Boost
Error: Could not find or load main class .util.logging.config.file=logging.properties
Caused by: java.lang.ClassNotFoundException: /util/logging/config/file=logging/properties
```

### Environment

  - **AWS Region  :** us-east-2
  - **AWS SaaS Boost Version :** commit 74e9047ce3f06779c645db392236c6dd7fe6fac9 (HEAD -> main, origin/main, origin/HEAD)
  - **Workload OS  (Linux or Windows) :** Windows

### Other

--- 

This is :bug: Bug Report

**Comment by 4patelr** [comment]
Hi @jrobbins-LiveData,

node v14.16.1 should be fine. Is there an error stack in the saas-boost-install.log that you can provide? What version of Java are you using?

**Comment by jrobbins-LiveData** [comment]
Hi @4patelr,

I don't see a file named `saas-boost-install.log` on my hard drive.  Where ought it be?

I installed Java per [the setup instructions](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#step-1---set-up-tooling):

```
java --version
openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode)
```

**Comment by brtrvn** [comment]
The error message is actually talking about java.util.logging not finding the logging.properties file -- we added this to quiet the warning messages from the AWS CLI when you use profiles for multiple AWS accounts. I will spin up a Windows instance to test and figure out what's going on.

**Comment by hariohmprasath** [comment]
Hi @jrobbins-LiveData,
Seems like -D without double quotes is causing an issue with powershell. 

Easier fix is to update the run command in Line 138 inside `install.ps1` to include double quotes after `java` command (like below):

```bash
java "-Djava.util.logging.config.file=logging.properties" -jar ${CURRENT_DIR}\installer\target\SaaSBoostInstall-1.0.0-shaded.jar
```

This will let you proceed further. Try it out and let us know.

**Comment by jrobbins-LiveData** [comment]
That fixed the problem -- thank you!

**Comment by AffiTheCreator** [comment]
I'm having the same issue

**Comment by hariohmprasath** [comment]
> That fixed the immediate problem -- thank you! [edited]
> 
> 
> 
> Apparently quite near the end of the process, it raised an error.
> 
> 
> 
> ```
> 
> CloudFormation Stack: sb-dev completed successfully.
> 
> Copy files to S3 web site bucket
> 
> Start build of AWS SaaS Boost React web application with yarn ...
> 
> ===========================================================
> 
> Installation Error: null
> 
> Please see detailed log file saas-boost-install.log
> 
> java.lang.NullPointerException
> 
>         at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:84)
> 
>         at java.base/java.lang.ProcessEnvironment.put(ProcessEnvironment.java:97)
> 
>         at java.base/java.lang.ProcessEnvironment.put(ProcessEnvironment.java:69)
> 
>         at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.buildAndCopyWebApp(SaaSBoostInstall.java:2257)
> 
>         at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:1459)
> 
>         at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:977)
> 
>         at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:198)
> 
> ```
> 
> 
> 
> The log doesn't seem to have any more context than this `NullPointerException`.

Hi,
The fix for this issue got merged yesterday so you can either do a git pull or look into this pull request and make the same changes in the local setup and retry again.

[https://github.com/awslabs/aws-saas-boost/pull/27](https://github.com/awslabs/aws-saas-boost/pull/27)
