### ISSUE TITLE
how to get the tenant id

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#286]
is tenant id get passed as an environment variable?

**Comment by PoeppingT** [comment]
Hey @qwudssd , if you're talking about accessing the Tenant ID from your Docker container yes, the Tenant ID is passed as an environment variable of the form `TENANT_ID`.

You can view all the environment variables currently passed to Application Service docker containers by viewing the [`ECSTaskDefintion` resource in the `tenant-onboarding-app.yaml`](https://github.com/awslabs/aws-saas-boost/blob/main/resources/tenant-onboarding-app.yaml#L484-L518) CloudFormation template.

Next time, please start a Q&A discussion so the answer can be left for others to find!
