### ISSUE TITLE
Sample Application service creation not working

### ISSUE THREAD

**Issue by manasgupta19** [awslabs/aws-saas-boost#287]
Sample Application service creation not working

### Reproduction Steps
Followed the steps to deploy a sample app. Created a service, clicked on submit. Nothing happened
<img width="1475" alt="Screenshot 2022-09-12 at 5 01 15 PM" src="https://user-images.githubusercontent.com/52977428/189642862-3e38025e-9400-4194-8009-a963e4a8218e.png">

### What did you expect to happen?
App to be created.

### What actually happened?
Nothing is happening.

### Environment

  - **AWS Region :** us-east-1
  - **AWS SaaS Boost Version:** latest one
  - **Workload OS  (Linux or Windows):** macOS M1 Pro

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Hello @manasgupta19 , at the top of your screenshot you can see that there are errors in the `main` service you have created which would need to be resolved before the configuration can be successfully submitted. Please verify that there are no errors in the below configurations.

Additionally, just submitting the AppConfig from this page will not create any tenant AWS resources in your account. Instead, you will need to 
1. upload a Docker image to each AppConfig service ECR repository
2. onboard a tenant using the `Tenants` page on the left

**Comment by manasgupta19** [comment]
There was no error while filling the Applications form. I have followed the steps exactly as mentioned in this page Step 7 https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md

**Comment by manasgupta19** [comment]
I have filled the Applications form as per the step 7 mentioned in the Getting started guide. 
https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md

Video part 1:
https://user-images.githubusercontent.com/52977428/189714070-095a1608-d99a-4351-80ac-14020173f70a.mov

**Comment by manasgupta19** [comment]
Video part 2:

https://user-images.githubusercontent.com/52977428/189716921-150b596b-6eb1-4642-81c4-7170aa74bb0b.mov

https://user-images.githubusercontent.com/52977428/189717067-333d2fc6-1f26-41ba-8e41-4c7f949e5ee7.mov

**Comment by PoeppingT** [comment]
Thanks for the detailed reproduction steps @manasgupta19 , you are correct that this is a bug. I have opened #289 to address this issue.
