### ISSUE TITLE
Instructions on "uploading an application image" are missing the image name

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-saas-boost#301]
This has been busted for a few months now, but finally documenting it.

When clicking the link here below:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1438064/191465291-07ea9e2b-25f7-4ff6-ac77-e7a7b28a6ff2.png">

(nit:  also missing a space before the word here above ^^)

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1438064/191465529-95a17154-e901-4f76-9060-65e0a748f3ff.png">

(missing the image name between the `/` and the `:latest` above ^^) 

This is an important part of the instructions, i feel.

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
In my test environment (built off of `main` at 176187a, this is what that same instruction looks like:

![Screen Shot 2022-09-21 at 12 19 07](https://user-images.githubusercontent.com/4009272/191591740-b0244c75-10be-474c-ac4c-c884dcfdeb0c.png)

Is it possible your ECR repository has not yet finished provisioning?
