### ISSUE TITLE
AWS China Support

### ISSUE THREAD

**Issue by brtrvn** [awslabs/aws-saas-boost#321]
Customers would like to take advantage of SaaS Boost in the [AWS China](https://www.amazonaws.cn/en/about-aws/china/) regions. Due to differences between the other global AWS commercial regions and the Beijing and Ningxia regions, SaaS Boost will not work as-is.

Changes required to support AWS China include offering a mechanism other than Amazon Cognito for system user authentication and authorization of both the admin web app as well as the API Gateway, a number of small changes to other AWS service interactions and other requirements.

- [x] #303 
- [x] #368 
- [x] #370 
- [x] #371 
- [x] #376 
- [x] #377 
- [x] #386 
- [x] #387 
- [x] #391

**Comment by PoeppingT** [comment]
This has been released with https://github.com/awslabs/aws-saas-boost/releases/tag/v2.1.0
