### ISSUE TITLE
S3 Storage Support

### ISSUE THREAD

**Issue by brtrvn** [awslabs/aws-saas-boost#325]
SaaS Boost should offer object storage as an application service extension as an alternative to managing files using the available network based shared file systems. This extension will be based on S3 and include best practices of encrypting contents at rest, private access, and logging enabled.

To limit the number of buckets provisioned, a single S3 bucket will be created per application with each service at its own prefix (folder). Inside the service's folder will be a folder for each onboarded tenant and strict IAM policies will protect cross tenant access.

The running application service code is responsible for using the Amazon S3 SDK to access the bucket. Environment variables will be passed to the container for both the bucket name as well as the prefix (folder) the container is allowed to access.
`S3_BUCKET`
`S3_ROOT_PREFIX`

- [x] #463

**Comment by tomg-formpak** [comment]
This will be a very useful feature. Looking forward to this.

**Comment by brtrvn** [comment]
Resolved with merge of #463
