### ISSUE TITLE
System User Service Support for Different Backing Implementations

### ISSUE THREAD

**Issue by brtrvn** [awslabs/aws-saas-boost#330]
To make SaaS Boost functional in AWS regions where Amazon Cognito is not available and to give customers greater choice in the identity provider for system users and API authorization, the System Users Service should support different implementations of its API.

The System User Service API will remain consistent, but we can configure which implementation to use at runtime. The first choices will be Amazon Cognito (as it works today) and, alternatively, a self-hosted [Keycloak](https://www.keycloak.org/) installation.

- [x] #383

**Comment by PoeppingT** [comment]
This has been released with https://github.com/awslabs/aws-saas-boost/releases/tag/v2.1.0
