### ISSUE TITLE
unable to make service private

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#357]
the box for 'Publicly accessible?', automatically becomes checked after submit, even if was unchecked before

saas boost branch: the latest version from master

**Comment by brtrvn** [comment]
Check the service config JSON in Systems Manager Parameter Store. It will be under a key named `/saas-boost/${Environment}/app/${ServiceName}/SERVICE_JSON`. There will be a property in the JSON `public` set to `true` or `false`. Note that for private services, the path property is ignored.

If your private service has `"public": false` in the JSON, then this is only a UI bug.
