### ISSUE TITLE
DB_NAME is empty

### ISSUE THREAD

**Issue by mpelts** [awslabs/aws-saas-boost#38]
"Database Name" field in **Application/Database/Database Initialization (Optional)** seems to be actually required. You can submit the configuration form with empty name, but then DB initialization (MariaDB) fails in saasfactory/configuration/DataSourceConfig.java [ln 119] with SQL syntax error because DB_NAME is empty.

### Environment

  - **AWS Region  :** eu-west-2
  - **AWS SaaS Boost Version :** v0
  - **Workload OS  (Linux or Windows) :** Linux (bundled test app)

--- 

This is :bug: Bug Report

**Comment by hariohmprasath** [comment]
Looks like having a database name is mandatory for sample app. We can update the documentation on the sample app to include this information. 

Other than that in general (if you are not using the sample app) database can be optional

**Comment by mpelts** [comment]
Doesn't it make sense to change the sample app to use a default DB name if it configuration doesn't provide that?

**Comment by brtrvn** [comment]
It used to have a fallback default name. I just removed it for fear of squashing someone's existing database if they were running it locally. We can update the documentation.

**Comment by dewickis** [comment]
This also appears to be the case with SQL Server instances. Task will remain in "PENDING" status without a DB_NAME.

**Comment by mpelts** [comment]
> It used to have a fallback default name. I just removed it for fear of squashing someone's existing database if they were running it locally. We can update the documentation.

According to the doc. a new cluster is provisioned for each tenant. Not sure how squashing existing DB is possible.

**Comment by brtrvn** [comment]
A new cluster is provided _when running in the SaaS Boost environment_. I was referring to someone running the sample app in Docker on their localhost connected to a database also on their localhost. Agree that this is a limited case. I've put back the default database name in the sample app if the DB_NAME environment variable is empty.
