### ISSUE TITLE
not able to update application configuration

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#392]
update failed when tried to modify the application configuration even if with no tenant deployed or provisioned
<img width="1546" alt="Screen Shot 2022-10-28 at 4 22 21 PM" src="https://user-images.githubusercontent.com/104920467/198726032-58cfed96-1512-4b69-a742-6b422474035d.png">

branch: latest main

**Comment by PoeppingT** [comment]
Hi @qwudssd , you can troubleshoot this by looking at the CloudWatch LogGroup for the Settings service for your environment. Go to the AWS Console, navigate to CloudWatch and click on "LogGroups" on the left. The LogGroup in question will have a name like `/aws/lambda/sb-${environment name}-settings-update-config`. The most recent logs should provide some additional information as to why the application configuration update failed.

**Comment by qwudssd** [comment]
okay thanks!

**Comment by qwudssd** [comment]
Hi i was not able to reproduce the issue and it works fine now.
