### ISSUE TITLE
ConflictingDomainExists

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#396]
Encountered this issue when trying to deploy a tenant. I have three services, one is public and the other two are private. The onboarding process failed for one of the private service with this error appeared in cloudformation
<img width="1768" alt="Screen Shot 2022-10-31 at 3 43 44 PM" src="https://user-images.githubusercontent.com/104920467/199097038-a8a992f8-6ee3-40f3-a309-10026cf540cb.png">

branch: main

**Comment by PoeppingT** [comment]
Hi @qwudssd , is this reproducible in your environment? If so, please provide in detail the configurations you have set for your environment, including the tiers, appConfig, and tenant onboardings.

**Comment by qwudssd** [comment]
Hi @PoeppingT yes i tried to onboard a tenant again just now and then the issue appeared again. Here are the pictures of the tiers, app configs and tenant settings. And only tellread is configured to provision a file system. On the onboarding page, i just noticed that the status of one of the tenants 'tenant' changed from failed to deploying today w/o any changes on the app config or images, not really sure why 

<img width="1551" alt="Screen Shot 2022-11-02 at 10 16 25 AM" src="https://user-images.githubusercontent.com/104920467/199513554-a1db38e3-cc39-436f-b81b-14976c2e5817.png">
<img width="1709" alt="Screen Shot 2022-11-02 at 10 05 08 AM" src="https://user-images.githubusercontent.com/104920467/199513676-894fbace-9603-4a5e-a351-257cd06aae70.png">
<img width="1758" alt="Screen Shot 2022-11-02 at 10 13 34 AM" src="https://user-images.githubusercontent.com/104920467/199513755-6998d545-21b4-4d77-98f0-c24524de95c8.png">

<img width="1783" alt="Screen Shot 2022-11-02 at 10 14 43 AM" src="https://user-images.githubusercontent.com/104920467/199513276-e4302bcf-3db3-4216-b2aa-d21c14ec4767.png">
<img width="1530" alt="Screen Shot 2022-11-02 at 10 15 31 AM" src="https://user-images.githubusercontent.com/104920467/199513350-6d755a69-af8d-4668-83be-cddbba5a9183.png">
<img width="1553" alt="Screen Shot 2022-11-02 at 10 15 49 AM" src="https://user-images.githubusercontent.com/104920467/199513408-b9706b14-6614-458e-8040-c92ff4009271.png">
<img width="1536" alt="Screen Shot 2022-11-02 at 10 16 04 AM" src="https://user-images.githubusercontent.com/104920467/199513438-0d1503e4-ba1c-46b4-a169-957973eecc0c.png">
<img width="1530" alt="Screen Shot 2022-11-02 at 10 16 14 AM" src="https://user-images.githubusercontent.com/104920467/199513499-82d36a4f-7407-4dfd-8b1b-e4295b216e5e.png">

**Comment by PoeppingT** [comment]
Thanks for the information @qwudssd , I can successfully reproduce the issue. It looks like this is due to each `tenant-onboarding-app` stack attempting to create a private ServiceDiscoveryNamespace attached to the tenant VPC when only one is allowed. The proper solution for this is to either create the ServiceDiscoveryNamespace in the `tenant-onboarding` stack or create a custom resource to only create the ServiceDiscoveryNamespace if it does not already exist in the `tenant-onboarding-app` stack.

Unfortunately there is currently no workaround for this, other than to make one of your private services public. We are working on a fix.

**Comment by qwudssd** [comment]
okay i see, thank you!
