### ISSUE TITLE
Metrics data not reaching redshift

### ISSUE THREAD

**Issue by raman231** [awslabs/aws-saas-boost#403]
Sample data generated by metrics-generator does not reach Redshift. It goes to S3 bucket fine, but gives following Destination error log in Kinesis Delivery Stream.

The COPY command contains a syntax error. ERROR: syntax error at or near "s3" Position: 1276

### Reproduction Steps

Generate some sample metrices with metrics-generator.
Check Kinesis Delivery stream destination error log

### What did you expect to happen?

Data should reach redshift

### What actually happened?

Error in destination logs

### Environment

  - **AWS Region  :us-east-1
  - **AWS SaaS Boost Version :v2.0.0-18-dirty
  - **Workload OS  (Linux or Windows) :Linux

### Other

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Closed by https://github.com/awslabs/aws-saas-boost/pull/407
