### ISSUE TITLE
HostedZone not getting stored correctly in parameter store

### ISSUE THREAD

**Issue by raman231** [awslabs/aws-saas-boost#404]
HostedZone not getting stored correctly in parameter store

### Reproduction Steps

Configure a service in Application
Enter domain name and other fields. For me there was an existing hosted zone in Route 53.
Submit
Check Summary page

### What did you expect to happen?

HostedZone Id should be stored in parameter store

### What actually happened?

HostedZone Id gets stored as N/A

### Environment

  - **AWS Region  :us-east-1
  - **AWS SaaS Boost Version :v2.0.0-18-dirty
  - **Workload OS  (Linux or Windows) :Linux

### Other

--- 

This is :bug: Bug Report

**Comment by raman231** [comment]
I noticed the core nested cfn stack is giving error during updates when the application configuration is saved.

It gives errors like following

Resource handler returned message: "Invalid request provided: test2 is reserved by AWS! (Service: Route53, Status Code: 400,


I have tried multiple subdomain names (dv1, dv2, dev2). it always gives error that it is reserved by AWS.
And it does not allow to change the subdomain in application configuration screen. shows error if I try to change that. I had to create separate SaaS boost installations to change domain names. but even after trying multiple options in sub-domains, none of them succeeds.

**Comment by raman231** [comment]
I figured the problem was that I was not giving proper FQDN in domain name field in application tab.
This resulted in HostedZone not being stored in parameter store since it could not find that domain name in Route 53.

Adding a validation to Domain name field so that it accepts only blank or valid domain name.

**Comment by PoeppingT** [comment]
Closed by https://github.com/awslabs/aws-saas-boost/pull/407
