### ISSUE TITLE
Cloud9 instructions should suggest installing jq

### ISSUE THREAD

**Issue by Jayasundar** [awslabs/aws-saas-boost#409]
### The Question
The build.sh script fail with line #45 jq not found

### Environment

  - **AWS SaaS Boost Version:** 2.49.1 (build be5fcf4)

### Other information
By default jq is not installed in Cloud9 deployment, need to install jq with following commend.

sudo yum install jq

**Comment by brtrvn** [comment]
@Jayasundar can you provide a little more context here? Which file are you referring to? That version (and that commit hash) doesn't exist in SaaS Boost.
