### ISSUE TITLE
Add ECS Exec has an option in Application settings

### ISSUE THREAD

**Issue by AffiTheCreator** [awslabs/aws-saas-boost#41]
Add option to Application settings to allow and disallow ECS exec from Saas Boost web app. 

### Use Case

For developing purposes, ECS exec makes a lot of sense hence #35, as of now we need to modify the tenant-onboarding.yaml to allow/disallow such tool.

#### Solution 1
Similar to the database and filesystem have a third element for developer tools such as ECS exec.

#### Solution 2
Add a checkbox to container settings element

This is a :rocket: Feature Request

**Comment by brtrvn** [comment]
Resolved with #493
