### ISSUE TITLE
 failed to create: [publicapi]

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#413]
failed to create publicapi while creating the admin app with following error in cloudformation
<img width="1107" alt="Screen Shot 2022-11-10 at 5 07 16 PM" src="https://user-images.githubusercontent.com/104920467/201216366-741f4816-6e42-4d2a-acb5-8c7b2dbb4f41.png">

branch: main

**Comment by brtrvn** [comment]
Thank you for the bug report. A fix is in process.
