### ISSUE TITLE
cant open the admin app after installation

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#415]
the deployment was successful but when I open the link and click on sign in this shows up
<img width="1280" alt="Screen Shot 2022-11-11 at 3 45 00 PM" src="https://user-images.githubusercontent.com/104920467/201428132-fa99058b-b026-4e5d-8369-4d7691b6a610.png">

<img width="1508" alt="Screen Shot 2022-11-11 at 3 42 16 PM" src="https://user-images.githubusercontent.com/104920467/201427958-4ad693c2-c557-4115-a59c-c7a9ac5620b3.png">

branch:latest main

**Comment by PoeppingT** [comment]
Hello @qwudssd , can you provide more information about your installation?
1. Is this error still present? 
2. Which identity provider did you choose when you created the environment?
3. By using the `inspect` feature of your browser, you can view network requests. Please find the request that was responded to with `invalid_scope` and copy the scope header here.

**Comment by qwudssd** [comment]
Hi, sorry the late response. The identity provider im using is Cognito. I've deleted the original one, but I've tried deploying again and it is now showing this
<img width="1652" alt="Screen Shot 2022-11-15 at 1 47 16 PM" src="https://user-images.githubusercontent.com/104920467/202001215-7c4ddfde-e4fc-4b3e-9d95-f0d3987ec5c7.png">

the request header is that is responded to with invalid_scope is:
:authority: d1lggiseg7u8wk.cloudfront.net
:method: GET
:path: /?error_description=invalid_scope&state=55ae50c93ffe4ad2bace1d0a858679b2&error=invalid_request
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
