### ISSUE TITLE
RDS provisioning failed for SQL Server Express during tenant onboarding 

### ISSUE THREAD

**Issue by dewickis** [awslabs/aws-saas-boost#43]
CF RDSInstance substack failed during tenant onboarding with the following error: 
DB Engine sqlserver-ex does not support encryption at rest (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 39dfa31e-c3c0-4028-899e-19d704362907; Proxy: null)

Error occurs during EncryptionKeyAlias CF logical ID.

### Reproduction Steps

Provision a tenant that requires SQL Server Express. RDSInstance substack will fail due to incompatible features.
### What did you expect to happen?
RDS for SQL Server Express would provision (original app uses Express) based on the menu options in Database configuration for the application.

### What actually happened?

Creation of the RDS instance failed during the CF deployment at the EncryptionKeyAlias logical ID, with the following error: 

DB Engine sqlserver-ex does not support encryption at rest (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 39dfa31e-c3c0-4028-899e-19d704362907; Proxy: null)

### Environment

  - **AWS Region  : us-west-2**
  - **AWS SaaS Boost Version : v0 - dev**
  - **Workload OS  (Linux or Windows) : Windows ASP.NET Framework 4.7.2**

### Other

--- 

This is :bug: Bug Report

**Comment by 4patelr** [comment]
Thanks Scott for reporting this issue. Will need to modify the tenant-onboarding-rds.yaml to set encryption based on whether the selected RDS supports it.

**Comment by brtrvn** [comment]
Resolved with 64b59593462b6461407cc897b74136da168857d2
