### ISSUE TITLE
Application not deployed in Saas boost

### ISSUE THREAD

**Issue by SudhaGanesanAkilandam** [awslabs/aws-saas-boost#430]
Installed SaaS Boost successfully.

container image having just tomcat, pushed into ECR.

Tenant creation got failed.

Not able to get logs.

Steps followed...
When trying to install AWS SaaS Boost v2.0.1 (latest) [link ](https://github.com/awslabs/aws-saas-boost/)But we are not able to install the AWS SaaS Boost Application on Windows.

Error : Installation Error: ParameterValue for ParameterKey Version is required (Service: CloudFormation, Status Code: 400, Request ID: 67b126b2-3d0b-4aaa-afb3-5edfe3c9ccb8) , Refer screenshot.

Installed prerequisite
Java 11
Amazon Corretto 11
Apache Maven - 3.8.6
AWS Command Line Interface version 2 - 2.8.12
Node 14 (LTS)
Yarn - 1.22.19
Python/3.9.11
visual studio

Download SaaS boost Application

git clone https://github.com/awslabs/aws-saas-boost ./aws-saas-boost

3 . Installation
Extract and navigate to Aws SaaS boost --> powershell .\install.ps1 --> provide inputs --> when installing gets Error, refer screen shot.

So that tried with previous version 2.0.0, 1.1.2 this version also had the same error, Now tried with initial release 1.0.0, same steps AWS SaaS boost installed successfully.
After installation Received mail for login details.

Login to AWS SaaS boost, Create and provide Application Details.

Upload image to AWS ECR (Elastic Container Registry) Repository. We created image based on [link](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#build-and-deploy-the-sample-application)

Provisioning tenant --> Failed

**Comment by PoeppingT** [comment]
Hi @SudhaGanesanAkilandam , thanks for opening this issue report. You say you are "Not able to get logs.", can you explain what you have tried? Are there no CloudWatchLogs LogGroups with `/ecs/` as a prefix? Have you verified that the ECS cluster was successfully deployed at the end of the created CodePipeline? There should be a CodePipeline with a name like `sb-tenant-${tenantId}-${serviceName}` which will start when the image is uploaded to ECR.

**Comment by SudhaGanesanAkilandam** [comment]
@PoeppingT thanks for suggest, When checking logs in AWS CodePipeline our image was not deployed in AWS ECS (Elastic Container Service ).

Steps followed...
When trying to install AWS SaaS Boost v2.0.1 (latest) [link ](https://github.com/awslabs/aws-saas-boost/)But we are not able to install the AWS SaaS Boost Application on Windows.

Error : Installation Error: ParameterValue for ParameterKey Version is required (Service: CloudFormation, Status Code: 400, Request ID: 67b126b2-3d0b-4aaa-afb3-5edfe3c9ccb8) , Refer screenshot.

1. Installed prerequisite
Java 11
Amazon Corretto 11
Apache Maven - 3.8.6
AWS Command Line Interface version 2 -  2.8.12
Node 14 (LTS)
Yarn - 1.22.19
Python/3.9.11
visual studio

2. Download SaaS boost Application

git clone https://github.com/awslabs/aws-saas-boost ./aws-saas-boost

3 . Installation
Extract and navigate to Aws SaaS boost -->  powershell .\install.ps1 --> provide inputs --> when installing gets Error, refer screen shot.

So that tried with previous version 2.0.0, 1.1.2 this version also had the same error, Now tried with initial release 1.0.0, same steps AWS SaaS boost installed successfully.
After installation Received mail for login details.

4. Login to AWS SaaS boost, Create and provide Application Details.

5. Upload image to AWS ECR (Elastic Container Registry) Repository. We created image based on [link ](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#build-and-deploy-the-sample-application)

6. Provisioning tenant --> Failed , When checking logs in AWS CodePipeline our image was not deployed in AWS ECS (Elastic Container Service ).
Reference link: https://github.com/
![TenantCreationCodepipeline2](https://user-images.githubusercontent.com/40356184/203333860-7f7682da-6456-44eb-b194-76c3afb3710b.png)
awslabs/aws-saas-boost/blob/main/docs/getting-started.md#build-and-deploy-the-sample-application
https://github.com/awslabs/aws-saas-b
![InstallationError](https://user-images.githubusercontent.com/40356184/203333824-68237867-c5d7-4f0c-bfe7-ae4d2fbe512d.png)
![TenantCreationCodepipeline1](https://user-images.githubusercontent.com/40356184/203333846-fe71b0fe-3451-483d-bfab-05e34deffa0d.png)

![AwsSaaSBoostAPPTenantfailed](https://user-images.githubusercontent.com/40356184/203333791-c745c233-2f48-46b9-b9f1-45b4a5779814.png)
oost/

**Comment by brtrvn** [comment]
@SudhaGanesanAkilandam I would go look at the CloudFormation console in your AWS account and see if there are any errors in the Events or Resources tabs for the different SaaS Boost stacks. You can also look at the saas-boost-install.log file on your workstation to see if there's a stack trace or more detail about the missing parameter value. It's unclear whether that is an error encountered by the installer after CloudFormation has finished, or an error coming back from CloudFormation.

It does look like you have at least a partially completed install (you can load the admin web app and log in).

You should also go to the ECS console, select the cluster for the tenant you onboarded, and under the Tasks tab look to see if there are Stopped tasks. You can select one, and then view the Logs tab for that tasks to see why your container is not launching.

**Comment by SudhaGanesanAkilandam** [comment]
@PoeppingT @brtrvn  for suggesting, Now AWS SaaS boost working fine.

RCA: Version Error due to downloading manually in github vs using cmd line.

when using download manually -- version error occurs, when using cmd it will works fine...
