### ISSUE TITLE
Deleting tenant throws failed state

### ISSUE THREAD

**Issue by AffiTheCreator** [awslabs/aws-saas-boost#46]
While trying to delete a tenant I got a DELETE_FAILED state. 
CloudFormation log ``` The vpc 'vpc-AAAAA9744f11d180' has dependencies and cannot be deleted. (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: AAAAAAA-547f-46b7-8e4b-937834713510; Proxy: null)``` 

### Reproduction Steps
I updated the container image prior to deleting the tenant - just a note
I'm trying to connect an Amazon Elasticsearch to a tenant running on fargate. 

#### Step 1
1. Create Amazon Elasticsearch Domain - For this I created a domain inside the tenant VPC 
2. Delete the Amazon Elasticsearch Domain 
#### Step 2 
1. Delete tenant in administration web app

### What did you expect to happen?

Tenant being deleted, with no status error. Since the Elasticsearch domain has deleted first and being that the only dependency I can think of because. The delete button has work for me before, I have done a few tenants deletes  with no error.

### What actually happened?
The tenant got deleted, but the VPC is still active, and I have a failed state even though the tenant got deleted. 

### Environment

  - **AWS Region  :eu-west-1
  - **AWS SaaS Boost Version : v0
  - **Workload OS  (Linux or Windows) : Linux

This is :bug: Bug Report

**Comment by AffiTheCreator** [comment]
I deleted a different tenant and now i get another error:

``` 
Resource handler returned message: "Error occurred during operation 'AWS::ElasticLoadBalancingV2::ListenerRuleUser: arn:aws:sts::35568XXXXX:assumed-role/sb-dev-onboarding-delete-tenant-role-eu-west-1/sb-dev-onboarding-delete is not authorized to perform: elasticloadbalancing:DeleteRule on resource: arn:aws:elasticloadbalancing:eu-west-1:35568XXXXX:listener-rule/app/tenant-ee083d20/ba08a074d81838e0/33dfc53fc64df935/79ab71adb74f6b01 (Service: ElasticLoadBalancingV2, Status Code: 403, Request ID: 9df13f3d-6b26-49ca-8ce1-c92a05062ae2, Extended Request ID: null)'." (RequestToken: 22c1c7fb-493c-a450-90b3-bb4a33813853, HandlerErrorCode: GeneralServiceException)
```

**Comment by aspcanada** [comment]
This may be related to #44. I noticed in the code that when deleting a tenant, the delete functionality was commented out and instead a tenant is disabled. Line 412 of TenantService.java

**Comment by 4patelr** [comment]
The issue seems to be related to the changes for #44 where the role used for the delete Lambda function is missing the deleteRule permission. Will take a look and add the permissions to the role.

**Comment by 4patelr** [comment]
Fix pushed to add resource for DeleteRule permission to role used for delete tenant in onboarding service. Requires to update the SaaS Boost environment.
