### ISSUE TITLE
Tenant access error

### ISSUE THREAD

**Issue by kohken-s** [awslabs/aws-saas-boost#461]
Thanks for your update.  

SaasBoost 2.1.0-8 installed
I have successfully created a tenant.
But Created  tenant access 404 error
Is this my problem?

S3-Backet-accesslog?
Saasboost admin colsole-access log is recorded

**Comment by PoeppingT** [comment]
Hi @kohken-s , welcome!

To help you we'll need a little more detail. Have you checked your ECS logs in AWS CloudWatch to verify response from your application loaded as a Docker container into ECS? To view this, go to AWS CloudWatch in your AWS console, click on "Log Groups" and search for `ecs` to find the logs for your ECS tasks.

**Comment by kohken-s** [comment]
Thank you advice.
I checked the Cloudwatch log.

sb-***-ecs-shutdown-services: no log.
sb-***-ecs-startup-services: no log.
/ecs/sb-***-tenant-***-main:  I found something to worry about.

 [mpm_prefork:notice] [pid 7] AH00169: caught SIGTERM, shutting down

Is it related?

![WS000007](https://user-images.githubusercontent.com/75592708/211146508-1b24b17e-ebad-4c32-9503-fb3bd9dc2745.JPG)

What else can I do?  I want to solve this problem somehow.

**Comment by kohken-s** [comment]
Hi Team.

I found out why I can't access my created tenant

Route53 
mydomain hostzone created before installation(with SSL)
and
Hosted zones created in Saasboost console - application settings

Couldn't access due to duplication.

I made it only for those added in the application settings.
If it already exists in Route53, is there a way to not create it?

Unable to add SSL and Creating the first tenant fails.
It seems that the tenant's A record cannot be added successfully

Please fix the instability

**Comment by kohken-s** [comment]
I think #257 is recurring. 
I would appreciate it if you could respond as soon as possible

SaasBoost v2.1.0-12 installed
Tenant created fails. 
![WS000008](https://user-images.githubusercontent.com/75592708/212582578-1b83b84f-eaa7-4663-9f09-6a7b38c6ee9b.JPG)

**Comment by kohken-s** [comment]
Hi Team.

This hosted zone overlap issue like the same issue in 257.

Is there any workaround currently?
and 
Are there any plans to address this issue?

Thanks in advance.
