### ISSUE TITLE
not able to deploy another tenant

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#469]
the onboarding process failed after provisioning when trying to deploy a second tenant with following error
<img width="1462" alt="Screen Shot 2023-01-27 at 3 32 30 PM" src="https://user-images.githubusercontent.com/104920467/215191457-7f93e2e2-716c-4ed4-86ac-d488e223743d.png">

**Comment by raman231** [comment]
@qwudssd please update you SaaS Boost installation taking in latest pull. this was addressed in a previous PR few weeks ago.

**Comment by qwudssd** [comment]
okay thank you!

**Comment by brtrvn** [comment]
@qwudssd did updating to the `HEAD` of the `main` branch resolve your issues?

**Comment by qwudssd** [comment]
yeah that resolved my issue! thank you!
