### ISSUE TITLE
expereincing 504 gateway time-out error and web socket connection error

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#472]
here are the errors: not too sure how to progress thru this

GET http://sb-dev-41-tenant-bd18df3c-380465062.us-west-2.elb.amazonaws.com/tr/logs/ 504 (Gateway Time-out)
<img width="985" alt="Screen Shot 2023-01-30 at 10 51 46 AM" src="https://user-images.githubusercontent.com/104920467/215526416-62e21f5e-c2fc-4e9e-b34a-8c4baa454150.png">

**Comment by PoeppingT** [comment]
Hi @qwudssd , this will happen when attempting to connect to a Tenant application if the application is not successfully started and is refusing connections. Is this the same tenant you refer to in https://github.com/awslabs/aws-saas-boost/issues/471 ?

**Comment by qwudssd** [comment]
okay, yes this is the same tenant
