### ISSUE TITLE
Onboarding Request Fail - sb-boost-tenant-app-sample CloudFormation error [EFS CREATED_FAILED]

### ISSUE THREAD

**Issue by kp-littlej** [awslabs/aws-saas-boost#512]
## Issue
After I installed SaaS Boost and setup tier info and Application, I created a tenant for testing.
In Cloudformation console, I checked the stack status. sb-boost-tenant stack was successfully completed.
But sb-boost-tenant-....-app-sample-... was not completed and the error(efs  CREATED_FAILED) occurred and rollback the all stacks.
I tried and tested it on the other aws environment(another AWS account) but they were also failed.

### Environment
* AWS Region: ap-northeast-2
* AWS SaaS Boost Version: v2.2.1
* Workload OS (Linux or Windows): Linux
* test date: 05/01 ~ now (Reference: AWS SaaS Boost Workshop)

**Comment by brtrvn** [comment]
See discussion in #513
