### ISSUE TITLE
Admin password output on CFN

### ISSUE THREAD

**Issue by pek77** [awslabs/aws-saas-boost#521]
If for some reason the customer cannot receive emails from Cognito, login the SaaS Boost console will cause confusion. Is it possible to add the password to the output of Cloudformation?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by brtrvn** [comment]
There is no way to get the Cognito-generated temporary password during User Pool user creation. We'd have to write a CloudFormation custom resource to be able to set the temporary password to a known value. Seems like a lot of overhead. What's the use case for not being able to receive the email from Cognito?

**Comment by pek77** [comment]
For customer workshop, we wanna pre config installation process before workshop for batch preparation

**Comment by brtrvn** [comment]
You could just have the workshop attendees run a script in Cloud9 to reset the admin password if you used a fake email to bootstrap the install.
`aws cognito-idp admin-set-user-password --user-pool-id $SYS_USERS_CUP --username admin --no-permanent --password $PASSWORD`

**Comment by pek77** [comment]
> You could just have the workshop attendees run a script in Cloud9 to reset the admin password if you used a fake email to bootstrap the install. `aws cognito-idp admin-set-user-password --user-pool-id $SYS_USERS_CUP --username admin --no-permanent --password $PASSWORD`

Got it, thx. I think should change cognito password too before login.
