### ISSUE TITLE
Tenant Onboarding failing with error while creating RDSSubnetGroup CF nested stack

### ISSUE THREAD

**Issue by prancst2004** [awslabs/aws-saas-boost#530]
Tenant onboarding stated provisoned but no tenant details are found in tenant tab. Whene checked the CF nested stack for RDS, it says 403 error -

Encountered a permissions error applying tags, please add required tag permissions. Retrying request without including tags. Resource handler returned message: "User: arn:aws:sts::367083322703:assumed-role/sb-dev-onboarding-svc-role-us-west-2/sb-dev-onboarding-events is not authorized to perform: rds:ListTagsForResource on resource: arn:aws:rds:us-west-2:367083322703:subgrp:sb-dev-rds-tenant-6ff31610-main because no identity-based policy allows the rds:ListTagsForResource action (Service: Rds, Status Code: 403, Request ID: e57d5a7a-93cd-4b5b-afd2-4c2e1b22a122)"

### Environment

  - **AWS Region  :us-west-2
  - **AWS SaaS Boost Version : Recent version
  - **Workload OS  (Linux or Windows) : Linux

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Resolved with #531
