### ISSUE TITLE
When there is a no tag docker image, can not create a new tanant in OnBoarding page

### ISSUE THREAD

**Issue by hanchenglin** [awslabs/aws-saas-boost#533]
### The Question
When there is a no tag docker image, if Icreate a new tanant in OnBoarding page, it is always validating. 
because background  throw a nullpointer error.

#### ECR
<img width="866" alt="スクリーンショット 2023-11-30 3 00 27" src="https://github.com/awslabs/aws-saas-boost/assets/11794032/339f9734-a9b0-4159-8d03-4c0b4fe6ebad">

##### Error log
<img width="1180" alt="スクリーンショット 2023-11-27 9 11 28" src="https://github.com/awslabs/aws-saas-boost/assets/11794032/40b226b1-d3c8-4689-bb93-1ad4134dfad6">

##### Source
https://github.com/awslabs/aws-saas-boost/blob/a36032b1c99f1bc745c1433dcf3f8798b70261cb/services/onboarding-service/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/OnboardingService.java#L1193

<img width="823" alt="スクリーンショット 2023-11-30 3 07 23" src="https://github.com/awslabs/aws-saas-boost/assets/11794032/81798a1d-ea44-423a-8cdd-a0639643cd4e">

### Environment

  - **AWS SaaS Boost Version:** 2.2.3

**Comment by brtrvn** [comment]
Interesting - I've never seen `ecr list-images` return an older image before a newer one. We can certainly be more defensive in the code to double check for `null`.
