### ISSUE TITLE
Stop the services when not in use

### ISSUE THREAD

**Issue by adilbasha** [awslabs/aws-saas-boost#70]
Stop the SaaS boost services when not in use

### Use Case

From a Dev project standpoint, we use the environment during working hours. we would like to see the feature in stopping the service in nonworking works.
For now, in fargate we are changing the autoscaling group to min 0 desired 0 and max as 0

### Proposed Solution

In the SaaS boast web console, under each tenant have the option to change the fargate ASG and also have the option to launch in the public subnet to avoid TSG cost

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by mahara13** [comment]
I am also interested in this functionality

**Comment by brtrvn** [comment]
Resolved with PR #109 
Be sure to re-run the installer after merging and choose `Update existing AWS SaaS Boost deployment`
