### ISSUE TITLE
Existing Route53 Hosted Zones are not reused for domain names

### ISSUE THREAD

**Issue by brtrvn** [awslabs/aws-saas-boost#74]
If a Route53 hosted zone already exists for a given domain name, we do not reuse it we create a new hosted zone every time.

### Reproduction Steps
Create a hosted zone in Route53 for a domain name
Tell SaaS Boost to use that domain name for your application

### What did you expect to happen?
Reuse the existing hosted zone for the domain name so that the DNS servers don't have to change and to reduce confusion when seeing multiple hosted zones all named the same.

### What actually happened?
A 2nd hosted zone for the same domain is created

--- 

This is :bug: Bug Report

**Comment by madanadit** [comment]
+1

**Comment by luiscosio** [comment]
+1

**Comment by adilbasha** [comment]
We are also facing the same issue, To overcome this, in the tenant-onboarding.yaml 
Properties:
       HostedZoneId: !Ref HostedZoneId
we harcoded the <HostedZoneId> of the correct Hostedzone

Even though it creates a new hosted zone but the recordset gets created in the correct hosted zone
Currently working on how to eliminate the duplicate one. will keep posted here

**Comment by rayson1223** [comment]
+1

**Comment by brtrvn** [comment]
This issue is resolved in the upcoming release.
