### ISSUE TITLE
Onboarding request page refreshes with application defaults

### ISSUE THREAD

**Issue by 4patelr** [awslabs/aws-saas-boost#79]
In the AWS SaaS Boost UI, the Onboarding Request page refreshes midstream to populate the Application defaults area. This leads to a poor user experience as data entered on the page is cleared out on the refresh.

### Reproduction Steps

1. Navigate to Onboarding
2. Click on Provision Tenant
3. Start entering the tenant name
4. In the case the application defaults have not been loaded from navigation to other areas of the app, the page will refresh when the data is loaded.

### What did you expect to happen?
I would expect the data to be loaded before rendering the page.

### Environment

  - **AWS Region  :**
  - **AWS SaaS Boost Version :**
  - **Workload OS  (Linux or Windows) :**

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Resolved in v2 with commit fdf2702

**Comment by brtrvn** [comment]
Merged into `main`
